# Generated by Django 4.0.5 on 2022-08-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('short_name', models.CharField(max_length=20, unique=True, verbose_name='nombre corto')),
                ('anulate', models.BooleanField(default=False, verbose_name='anulado')),
            ],
        ),
    ]
