# Generated by Django 4.0 on 2022-09-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_alter_empleado_avatar_alter_empleado_habilidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
    ]
